### ISSUE TITLE
QUIC pacing in RFC 9002

### ISSUE THREAD

**Issue by gorryfair** [mwelzl/draft-ccwg-ratelimited-increase#12]
We currently say: A sender that paces packets (see Section 7.7) might delay sending packets and not fully utilize the congestion window due to this delay. A sender SHOULD NOT consider itself application limited if it would have fully utilized the congestion window without pacing delay.

... Ah this is MUCH more complicated.
I suggest there are two uses of pacing by a transport protocol:
1. {Burst Mitigation}. QUIC and TCP recommend the use of pacing to avoid generating long bursts. 
This adds a small fixed delay after sending a burst of 10 contiguous packets, 
to avoid exceeding the interface buffers of network equipment. 
2. {Rate-Based Pacing}.
This pacing is designed to avoid triggering 
congestion by limiting the rate near that of the presumed bottleneck, as in BBR, Vegas.

The 1st doesn't really cause under use of cwnd, the latter can. Do we agree on this?

**Comment by mwelzl** [comment]
I disagree with your assessment - also because the burst mitigation stuff doesn't really exist anywhere that I'd know of?

I wonder where you have the 10 packets from, surely not from an RFC?   There's a fixed hardcoded 10 packet burst in Linux pacing, maybe that's what you think of?  but that's only the first 10 packets of IW (and repeating every 2^32 packets  :-D  ) and never again.

I think there are three possible approaches:
1) Just leave the statement there for now, knowing that this may need tweaking. I tend towards this.
2) Remove it.
3) Say something like [pacing to be discussed in a future version]

What should we do?

As a side note, I think that pacing might in fact not make a difference for senders implementing our maxFs rule - because this essentially allows to increase "as normal" on the basis of the last RTT, and pacing happens in sub-RTT time scales...  i.e., the rule should normally make a paced sender automatically apply the rules of a "greedy" sender, removing the need to even say something about pacing perhaps?

**Comment by gorryfair** [comment]
The 10 packets is the IW in quic, and burst mitigation is the reason this was chosen, and so max burst size is linked to this. I observed that this text was never greatly precise:-).

I think some quic implementations do  burst-mitigation; and some do rate-based pacing. 

So the part I feel uncomfortable in our test is the citation of sect 7.7. Could we just remove that cross reference?

**Comment by mwelzl** [comment]
Sure!  Just
```(see Section 7.7)```
and leave all else as it is?

**Comment by gorryfair** [comment]
Curiously, "yes - please jusr delete the bracketed text" - because the statement is true of pacing in general:-).

**Comment by mwelzl** [comment]
Ah, I see, I have this there because it's a textual quote. Well, we will be forgiven for removing that section reference...
